pub(super) const TECH_KEYWORDS: &[&str] = &[
    "javascript",
    "typescript",
    "python",
    "rust",
    "go",
    "golang",
    "java",
    "c#",
    "c++",
    "ruby",
    "php",
    "swift",
    "kotlin",
    "scala",
    "elixir",
    "dart",
    "lua",
    "r",
    "solidity",
    "sql",
    "graphql",
    "html",
    "html5",
    "css",
    "css3",
    "sass",
    "less",
    "react",
    "next.js",
    "nextjs",
    "vue",
    "vue.js",
    "nuxt",
    "angular",
    "svelte",
    "remix",
    "gatsby",
    "tailwind",
    "tailwindcss",
    "bootstrap",
    "material ui",
    "chakra ui",
    "shadcn",
    "redux",
    "zustand",
    "mobx",
    "react query",
    "tanstack",
    "webpack",
    "vite",
    "esbuild",
    "rollup",
    "storybook",
    "node.js",
    "nodejs",
    "express",
    "fastapi",
    "flask",
    "django",
    "nestjs",
    "spring",
    "spring boot",
    "rails",
    "laravel",
    "actix",
    "axum",
    "gin",
    "fiber",
    "hono",
    "trpc",
    "rest",
    "restful",
    "grpc",
    "postgresql",
    "postgres",
    "mysql",
    "mariadb",
    "sqlite",
    "mongodb",
    "redis",
    "dynamodb",
    "cassandra",
    "elasticsearch",
    "clickhouse",
    "supabase",
    "firebase",
    "prisma",
    "drizzle",
    "typeorm",
    "sequelize",
    "sqlx",
    "knex",
    "docker",
    "kubernetes",
    "k8s",
    "terraform",
    "ansible",
    "aws",
    "gcp",
    "azure",
    "vercel",
    "netlify",
    "heroku",
    "digitalocean",
    "cloudflare",
    "nginx",
    "caddy",
    "ci/cd",
    "github actions",
    "gitlab ci",
    "jenkins",
    "circleci",
    "git",
    "github",
    "gitlab",
    "bitbucket",
    "jira",
    "confluence",
    "figma",
    "postman",
    "linux",
    "unix",
    "jest",
    "vitest",
    "cypress",
    "playwright",
    "selenium",
    "mocha",
    "pytest",
    "testing library",
    "react testing library",
    "pandas",
    "numpy",
    "pytorch",
    "tensorflow",
    "scikit-learn",
    "kafka",
    "rabbitmq",
    "bullmq",
    "sqs",
    "nats",
    "blockchain",
    "ethereum",
    "solana",
    "web3",
    "smart contracts",
    "ethers.js",
    "hardhat",
    "foundry",
    "react native",
    "flutter",
    "ios",
    "android",
    "swiftui",
    "jetpack compose",
    "microservices",
    "monorepo",
    "websocket",
    "websockets",
    "ssr",
    "ssg",
    "api",
    "oauth",
    "jwt",
    "agile",
    "scrum",
    "kanban",
];

pub(super) const AMBIGUOUS_LANG: &[&str] = &["go", "r"];

pub(super) const EXPECTED_SECTIONS: &[(&str, &[&str])] = &[
    ("contact", &["email", "phone", "linkedin", "github", "@"]),
    ("summary", &["summary", "about", "objective", "profile"]),
    (
        "experience",
        &["experience", "work", "employment", "professional"],
    ),
    (
        "education",
        &["education", "university", "bachelor", "master", "degree"],
    ),
    ("skills", &["skills", "technologies", "tech stack"]),
];

pub(super) const NICE_CASE: &[(&str, &str)] = &[
    ("javascript", "JavaScript"),
    ("typescript", "TypeScript"),
    ("golang", "Go"),
    ("php", "PHP"),
    ("sql", "SQL"),
    ("graphql", "GraphQL"),
    ("html", "HTML"),
    ("html5", "HTML5"),
    ("css", "CSS"),
    ("css3", "CSS3"),
    ("next.js", "Next.js"),
    ("nextjs", "Next.js"),
    ("nodejs", "Node.js"),
    ("node.js", "Node.js"),
    ("nestjs", "NestJS"),
    ("vue.js", "Vue.js"),
    ("fastapi", "FastAPI"),
    ("tailwind", "Tailwind CSS"),
    ("tailwindcss", "Tailwind CSS"),
    ("material ui", "Material UI"),
    ("chakra ui", "Chakra UI"),
    ("mobx", "MobX"),
    ("tanstack", "TanStack"),
    ("esbuild", "esbuild"),
    ("trpc", "tRPC"),
    ("rest", "REST"),
    ("restful", "RESTful"),
    ("grpc", "gRPC"),
    ("postgresql", "PostgreSQL"),
    ("postgres", "PostgreSQL"),
    ("mysql", "MySQL"),
    ("mariadb", "MariaDB"),
    ("sqlite", "SQLite"),
    ("mongodb", "MongoDB"),
    ("dynamodb", "DynamoDB"),
    ("clickhouse", "ClickHouse"),
    ("typeorm", "TypeORM"),
    ("sqlx", "SQLx"),
    ("k8s", "Kubernetes"),
    ("aws", "AWS"),
    ("gcp", "GCP"),
    ("digitalocean", "DigitalOcean"),
    ("ci/cd", "CI/CD"),
    ("github actions", "GitHub Actions"),
    ("gitlab ci", "GitLab CI"),
    ("circleci", "CircleCI"),
    ("github", "GitHub"),
    ("gitlab", "GitLab"),
    ("ios", "iOS"),
    ("swiftui", "SwiftUI"),
    ("websocket", "WebSocket"),
    ("websockets", "WebSockets"),
    ("ssr", "SSR"),
    ("ssg", "SSG"),
    ("api", "API"),
    ("oauth", "OAuth"),
    ("jwt", "JWT"),
    ("rabbitmq", "RabbitMQ"),
    ("bullmq", "BullMQ"),
    ("sqs", "SQS"),
    ("nats", "NATS"),
    ("numpy", "NumPy"),
    ("pytorch", "PyTorch"),
    ("tensorflow", "TensorFlow"),
    ("scikit-learn", "scikit-learn"),
    ("pandas", "pandas"),
    ("pytest", "pytest"),
    ("ethers.js", "ethers.js"),
    ("react native", "React Native"),
    ("jetpack compose", "Jetpack Compose"),
];

pub(super) const WEAK_VERBS_EN: &[(&str, &[&str])] = &[
    (
        "worked",
        &["engineered", "developed", "delivered", "executed"],
    ),
    (
        "helped",
        &["facilitated", "enabled", "accelerated", "mentored"],
    ),
    (
        "did",
        &["accomplished", "executed", "achieved", "performed"],
    ),
    ("made", &["built", "designed", "produced", "constructed"]),
    ("used", &["leveraged", "utilized", "employed", "applied"]),
    (
        "handled",
        &["managed", "orchestrated", "directed", "oversaw"],
    ),
    (
        "was responsible for",
        &["led", "owned", "drove", "spearheaded"],
    ),
    ("responsible for", &["led", "owned", "drove", "spearheaded"]),
    (
        "participated",
        &["contributed", "collaborated", "co‑led", "engaged"],
    ),
    (
        "assisted",
        &["supported", "enabled", "facilitated", "guided"],
    ),
    (
        "involved in",
        &["contributed to", "drove", "co‑led", "championed"],
    ),
    ("tried", &["attempted", "pursued", "piloted", "prototyped"]),
    ("got", &["acquired", "obtained", "secured", "attained"]),
    (
        "improved",
        &["optimized", "enhanced", "boosted", "elevated"],
    ),
    (
        "changed",
        &["transformed", "revamped", "restructured", "redesigned"],
    ),
    (
        "showed",
        &["demonstrated", "illustrated", "showcased", "proved"],
    ),
    (
        "gave",
        &["delivered", "presented", "provided", "contributed"],
    ),
    (
        "went",
        &["transitioned", "migrated", "advanced", "progressed"],
    ),
    ("ran", &["managed", "executed", "orchestrated", "operated"]),
    (
        "set up",
        &["established", "configured", "implemented", "architected"],
    ),
    (
        "put together",
        &["assembled", "compiled", "organized", "formulated"],
    ),
    (
        "looked into",
        &["investigated", "researched", "analyzed", "evaluated"],
    ),
    (
        "took care of",
        &["managed", "maintained", "administered", "oversaw"],
    ),
];
